[build]
  command = "npm install"
  publish = "public"


[[headers]]
  for = "/*" # Apply to all paths
  [headers.values]
    Access-Control-Allow-Origin = "*" # Allow all origins to access your resources
    Access-Control-Allow-Methods = "GET, POST, OPTIONS" # Specify allowed HTTP methods
    Access-Control-Allow-Headers = "Content-Type, Authorization" # Specify allowed headers

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/css/*"
  to = "/images/"
  status = 200

[[redirects]]
  from = "/images/*"
  to = "/images/"
  status = 200


[[redirects]]
  from = "/api"
  to = "/api/index.json"
  status = 200

[[redirects]]
  from = "/dest-images/*"
  to = "/dest-images/"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
  force = true
